insert into SL_ORDERS(ID, NAME, TOTAL_AMOUNT ) values (1, 'Muthu', 500);
insert into SL_ORDERS(ID, NAME, TOTAL_AMOUNT ) values (2, 'Germany', 600);
insert into SL_ORDERS(ID, NAME, TOTAL_AMOUNT ) values (3, 'England', 700);
insert into SL_ORDERS(ID, NAME, TOTAL_AMOUNT ) values (4, 'Australia', 800);
insert into SL_ORDERS(ID, NAME, TOTAL_AMOUNT ) values (5, 'Canada', 850);
insert into SL_ORDERS(ID, NAME, TOTAL_AMOUNT ) values (6, 'America', 900);
insert into SL_ORDERS(ID, NAME, TOTAL_AMOUNT ) values (7, 'China', 950);
insert into SL_ORDERS(ID, NAME, TOTAL_AMOUNT ) values (8, 'Japan', 975);
insert into SL_ITEMS(ID,  NAME, QUANTITY, PRICE, AMOUNT , ORDERS_ID) values (1, 'Fewikwik', 1000, 599, 599, 1);
insert into SL_ITEMS(ID,  NAME, QUANTITY, PRICE, AMOUNT , ORDERS_ID) values (2, 'CASIO', 1000, 699, 699, 1);
insert into SL_ITEMS(ID,  NAME, QUANTITY, PRICE, AMOUNT , ORDERS_ID) values (3, 'England', 1000, 699, 699, 1);
insert into SL_ITEMS(ID,  NAME, QUANTITY, PRICE, AMOUNT , ORDERS_ID) values (4, 'Australia', 1000, 699, 699, 1);
insert into SL_ITEMS(ID,  NAME, QUANTITY, PRICE, AMOUNT , ORDERS_ID) values (5, 'Canada', 1000, 699, 699, 1);
